name: netflix_clone
description: A Netflix clone made with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/

  fonts:
    - family: NetflixSans
      fonts:
        - asset: assets/fonts/NetflixSans-Bold.otf
        - asset: assets/fonts/NetflixSans-Light.otf
        - asset: assets/fonts/NetflixSans-Medium.otf
        - asset: assets/fonts/NetflixSans-Regular.otf
